apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-function-calling
  labels:
    app: function-calling
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: function-calling 