# permissions for end users to edit clickhouses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/managed-by: kustomize
  name: clickhouse-editor-role
rules:
- apiGroups:
  - app.aiops.com
  resources:
  - clickhouses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.aiops.com
  resources:
  - clickhouses/status
  verbs:
  - get
