apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: aiops.aiops.geektime.com
spec:
  group: aiops.geektime.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                model:
                  type: string
                prompt:
                  type: string
                target:
                  type: string
              required: ["model", "prompt", "target"]
  scope: Namespaced
  names:
    plural: aiops
    singular: aiops
    kind: AIOps
    shortNames:
      - ai 
